/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DzienRouteImport } from './routes/dzien'
import { Route as ZadaniaRouteImport } from './routes/zadania'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DzienRoute = DzienRouteImport.update({
  id: '/dzien',
  path: '/dzien',
  getParentRoute: () => rootRouteImport,
} as any)
const ZadaniaRoute = ZadaniaRouteImport.update({
  id: '/zadania',
  path: '/zadania',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dzien': typeof DzienRoute
  '/zadania': typeof ZadaniaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dzien': typeof DzienRoute
  '/zadania': typeof ZadaniaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dzien': typeof DzienRoute
  '/zadania': typeof ZadaniaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dzien' | '/zadania'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dzien' | '/zadania'
  id: '__root__' | '/' | '/dzien' | '/zadania'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DzienRoute: typeof DzienRoute
  ZadaniaRoute: typeof ZadaniaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dzien': {
      id: '/dzien'
      path: '/dzien'
      fullPath: '/dzien'
      preLoaderRoute: typeof DzienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zadania': {
      id: '/zadania'
      path: '/zadania'
      fullPath: '/zadania'
      preLoaderRoute: typeof ZadaniaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DzienRoute: DzienRoute,
  ZadaniaRoute: ZadaniaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
