/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DzienRouteImport } from './routes/dzien'
import { Route as UstawieniaRouteImport } from './routes/ustawienia'
import { Route as ZadaniaRouteImport } from './routes/zadania'
import { Route as SkupienieIndexRouteImport } from './routes/skupienie/index'
import { Route as SkupienieAplikacjeRouteImport } from './routes/skupienie/aplikacje'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DzienRoute = DzienRouteImport.update({
  id: '/dzien',
  path: '/dzien',
  getParentRoute: () => rootRouteImport,
} as any)
const UstawieniaRoute = UstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => rootRouteImport,
} as any)
const ZadaniaRoute = ZadaniaRouteImport.update({
  id: '/zadania',
  path: '/zadania',
  getParentRoute: () => rootRouteImport,
} as any)
const SkupienieIndexRoute = SkupienieIndexRouteImport.update({
  id: '/skupienie/',
  path: '/skupienie/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkupienieAplikacjeRoute = SkupienieAplikacjeRouteImport.update({
  id: '/skupienie/aplikacje',
  path: '/skupienie/aplikacje',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dzien': typeof DzienRoute
  '/ustawienia': typeof UstawieniaRoute
  '/zadania': typeof ZadaniaRoute
  '/skupienie/aplikacje': typeof SkupienieAplikacjeRoute
  '/skupienie/': typeof SkupienieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dzien': typeof DzienRoute
  '/ustawienia': typeof UstawieniaRoute
  '/zadania': typeof ZadaniaRoute
  '/skupienie/aplikacje': typeof SkupienieAplikacjeRoute
  '/skupienie': typeof SkupienieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dzien': typeof DzienRoute
  '/ustawienia': typeof UstawieniaRoute
  '/zadania': typeof ZadaniaRoute
  '/skupienie/aplikacje': typeof SkupienieAplikacjeRoute
  '/skupienie/': typeof SkupienieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dzien'
    | '/ustawienia'
    | '/zadania'
    | '/skupienie/aplikacje'
    | '/skupienie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dzien'
    | '/ustawienia'
    | '/zadania'
    | '/skupienie/aplikacje'
    | '/skupienie'
  id:
    | '__root__'
    | '/'
    | '/dzien'
    | '/ustawienia'
    | '/zadania'
    | '/skupienie/aplikacje'
    | '/skupienie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DzienRoute: typeof DzienRoute
  UstawieniaRoute: typeof UstawieniaRoute
  ZadaniaRoute: typeof ZadaniaRoute
  SkupienieAplikacjeRoute: typeof SkupienieAplikacjeRoute
  SkupienieIndexRoute: typeof SkupienieIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dzien': {
      id: '/dzien'
      path: '/dzien'
      fullPath: '/dzien'
      preLoaderRoute: typeof DzienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustawienia': {
      id: '/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof UstawieniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zadania': {
      id: '/zadania'
      path: '/zadania'
      fullPath: '/zadania'
      preLoaderRoute: typeof ZadaniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skupienie/': {
      id: '/skupienie/'
      path: '/skupienie'
      fullPath: '/skupienie/'
      preLoaderRoute: typeof SkupienieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skupienie/aplikacje': {
      id: '/skupienie/aplikacje'
      path: '/skupienie/aplikacje'
      fullPath: '/skupienie/aplikacje'
      preLoaderRoute: typeof SkupienieAplikacjeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DzienRoute: DzienRoute,
  UstawieniaRoute: UstawieniaRoute,
  ZadaniaRoute: ZadaniaRoute,
  SkupienieAplikacjeRoute: SkupienieAplikacjeRoute,
  SkupienieIndexRoute: SkupienieIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
