/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DzienRouteImport } from './routes/dzien'
import { Route as StatystykiRouteImport } from './routes/statystyki'
import { Route as WioskaRouteImport } from './routes/wioska'
import { Route as ZadaniaRouteImport } from './routes/zadania'
import { Route as SkupienieIndexRouteImport } from './routes/skupienie/index'
import { Route as SkupienieAplikacjeRouteImport } from './routes/skupienie/aplikacje'
import { Route as UstawieniaIndexRouteImport } from './routes/ustawienia/index'
import { Route as UstawieniaDzienRouteImport } from './routes/ustawienia/dzien'
import { Route as UstawieniaKontoRouteImport } from './routes/ustawienia/konto'
import { Route as UstawieniaNakladkaRouteImport } from './routes/ustawienia/nakladka'
import { Route as UstawieniaPowiadomieniaRouteImport } from './routes/ustawienia/powiadomienia'
import { Route as UstawieniaProfilRouteImport } from './routes/ustawienia/profil'
import { Route as UstawieniaUprawnieniaRouteImport } from './routes/ustawienia/uprawnienia'
import { Route as UstawieniaWygladRouteImport } from './routes/ustawienia/wyglad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DzienRoute = DzienRouteImport.update({
  id: '/dzien',
  path: '/dzien',
  getParentRoute: () => rootRouteImport,
} as any)
const StatystykiRoute = StatystykiRouteImport.update({
  id: '/statystyki',
  path: '/statystyki',
  getParentRoute: () => rootRouteImport,
} as any)
const WioskaRoute = WioskaRouteImport.update({
  id: '/wioska',
  path: '/wioska',
  getParentRoute: () => rootRouteImport,
} as any)
const ZadaniaRoute = ZadaniaRouteImport.update({
  id: '/zadania',
  path: '/zadania',
  getParentRoute: () => rootRouteImport,
} as any)
const SkupienieIndexRoute = SkupienieIndexRouteImport.update({
  id: '/skupienie/',
  path: '/skupienie/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkupienieAplikacjeRoute = SkupienieAplikacjeRouteImport.update({
  id: '/skupienie/aplikacje',
  path: '/skupienie/aplikacje',
  getParentRoute: () => rootRouteImport,
} as any)
const UstawieniaIndexRoute = UstawieniaIndexRouteImport.update({
  id: '/ustawienia/',
  path: '/ustawienia/',
  getParentRoute: () => rootRouteImport,
} as any)
const UstawieniaDzienRoute = UstawieniaDzienRouteImport.update({
  id: '/ustawienia/dzien',
  path: '/ustawienia/dzien',
  getParentRoute: () => rootRouteImport,
} as any)
const UstawieniaKontoRoute = UstawieniaKontoRouteImport.update({
  id: '/ustawienia/konto',
  path: '/ustawienia/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const UstawieniaNakladkaRoute = UstawieniaNakladkaRouteImport.update({
  id: '/ustawienia/nakladka',
  path: '/ustawienia/nakladka',
  getParentRoute: () => rootRouteImport,
} as any)
const UstawieniaPowiadomieniaRoute = UstawieniaPowiadomieniaRouteImport.update({
  id: '/ustawienia/powiadomienia',
  path: '/ustawienia/powiadomienia',
  getParentRoute: () => rootRouteImport,
} as any)
const UstawieniaProfilRoute = UstawieniaProfilRouteImport.update({
  id: '/ustawienia/profil',
  path: '/ustawienia/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const UstawieniaUprawnieniaRoute = UstawieniaUprawnieniaRouteImport.update({
  id: '/ustawienia/uprawnienia',
  path: '/ustawienia/uprawnienia',
  getParentRoute: () => rootRouteImport,
} as any)
const UstawieniaWygladRoute = UstawieniaWygladRouteImport.update({
  id: '/ustawienia/wyglad',
  path: '/ustawienia/wyglad',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dzien': typeof DzienRoute
  '/statystyki': typeof StatystykiRoute
  '/wioska': typeof WioskaRoute
  '/zadania': typeof ZadaniaRoute
  '/skupienie/aplikacje': typeof SkupienieAplikacjeRoute
  '/ustawienia/dzien': typeof UstawieniaDzienRoute
  '/ustawienia/konto': typeof UstawieniaKontoRoute
  '/ustawienia/nakladka': typeof UstawieniaNakladkaRoute
  '/ustawienia/powiadomienia': typeof UstawieniaPowiadomieniaRoute
  '/ustawienia/profil': typeof UstawieniaProfilRoute
  '/ustawienia/uprawnienia': typeof UstawieniaUprawnieniaRoute
  '/ustawienia/wyglad': typeof UstawieniaWygladRoute
  '/skupienie/': typeof SkupienieIndexRoute
  '/ustawienia/': typeof UstawieniaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dzien': typeof DzienRoute
  '/statystyki': typeof StatystykiRoute
  '/wioska': typeof WioskaRoute
  '/zadania': typeof ZadaniaRoute
  '/skupienie/aplikacje': typeof SkupienieAplikacjeRoute
  '/ustawienia/dzien': typeof UstawieniaDzienRoute
  '/ustawienia/konto': typeof UstawieniaKontoRoute
  '/ustawienia/nakladka': typeof UstawieniaNakladkaRoute
  '/ustawienia/powiadomienia': typeof UstawieniaPowiadomieniaRoute
  '/ustawienia/profil': typeof UstawieniaProfilRoute
  '/ustawienia/uprawnienia': typeof UstawieniaUprawnieniaRoute
  '/ustawienia/wyglad': typeof UstawieniaWygladRoute
  '/skupienie': typeof SkupienieIndexRoute
  '/ustawienia': typeof UstawieniaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dzien': typeof DzienRoute
  '/statystyki': typeof StatystykiRoute
  '/wioska': typeof WioskaRoute
  '/zadania': typeof ZadaniaRoute
  '/skupienie/aplikacje': typeof SkupienieAplikacjeRoute
  '/ustawienia/dzien': typeof UstawieniaDzienRoute
  '/ustawienia/konto': typeof UstawieniaKontoRoute
  '/ustawienia/nakladka': typeof UstawieniaNakladkaRoute
  '/ustawienia/powiadomienia': typeof UstawieniaPowiadomieniaRoute
  '/ustawienia/profil': typeof UstawieniaProfilRoute
  '/ustawienia/uprawnienia': typeof UstawieniaUprawnieniaRoute
  '/ustawienia/wyglad': typeof UstawieniaWygladRoute
  '/skupienie/': typeof SkupienieIndexRoute
  '/ustawienia/': typeof UstawieniaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dzien'
    | '/statystyki'
    | '/wioska'
    | '/zadania'
    | '/skupienie/aplikacje'
    | '/ustawienia/dzien'
    | '/ustawienia/konto'
    | '/ustawienia/nakladka'
    | '/ustawienia/powiadomienia'
    | '/ustawienia/profil'
    | '/ustawienia/uprawnienia'
    | '/ustawienia/wyglad'
    | '/skupienie/'
    | '/ustawienia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dzien'
    | '/statystyki'
    | '/wioska'
    | '/zadania'
    | '/skupienie/aplikacje'
    | '/ustawienia/dzien'
    | '/ustawienia/konto'
    | '/ustawienia/nakladka'
    | '/ustawienia/powiadomienia'
    | '/ustawienia/profil'
    | '/ustawienia/uprawnienia'
    | '/ustawienia/wyglad'
    | '/skupienie'
    | '/ustawienia'
  id:
    | '__root__'
    | '/'
    | '/dzien'
    | '/statystyki'
    | '/wioska'
    | '/zadania'
    | '/skupienie/aplikacje'
    | '/ustawienia/dzien'
    | '/ustawienia/konto'
    | '/ustawienia/nakladka'
    | '/ustawienia/powiadomienia'
    | '/ustawienia/profil'
    | '/ustawienia/uprawnienia'
    | '/ustawienia/wyglad'
    | '/skupienie/'
    | '/ustawienia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DzienRoute: typeof DzienRoute
  StatystykiRoute: typeof StatystykiRoute
  WioskaRoute: typeof WioskaRoute
  ZadaniaRoute: typeof ZadaniaRoute
  SkupienieAplikacjeRoute: typeof SkupienieAplikacjeRoute
  UstawieniaDzienRoute: typeof UstawieniaDzienRoute
  UstawieniaKontoRoute: typeof UstawieniaKontoRoute
  UstawieniaNakladkaRoute: typeof UstawieniaNakladkaRoute
  UstawieniaPowiadomieniaRoute: typeof UstawieniaPowiadomieniaRoute
  UstawieniaProfilRoute: typeof UstawieniaProfilRoute
  UstawieniaUprawnieniaRoute: typeof UstawieniaUprawnieniaRoute
  UstawieniaWygladRoute: typeof UstawieniaWygladRoute
  SkupienieIndexRoute: typeof SkupienieIndexRoute
  UstawieniaIndexRoute: typeof UstawieniaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dzien': {
      id: '/dzien'
      path: '/dzien'
      fullPath: '/dzien'
      preLoaderRoute: typeof DzienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statystyki': {
      id: '/statystyki'
      path: '/statystyki'
      fullPath: '/statystyki'
      preLoaderRoute: typeof StatystykiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wioska': {
      id: '/wioska'
      path: '/wioska'
      fullPath: '/wioska'
      preLoaderRoute: typeof WioskaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zadania': {
      id: '/zadania'
      path: '/zadania'
      fullPath: '/zadania'
      preLoaderRoute: typeof ZadaniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skupienie/': {
      id: '/skupienie/'
      path: '/skupienie'
      fullPath: '/skupienie/'
      preLoaderRoute: typeof SkupienieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skupienie/aplikacje': {
      id: '/skupienie/aplikacje'
      path: '/skupienie/aplikacje'
      fullPath: '/skupienie/aplikacje'
      preLoaderRoute: typeof SkupienieAplikacjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustawienia/': {
      id: '/ustawienia/'
      path: '/ustawienia'
      fullPath: '/ustawienia/'
      preLoaderRoute: typeof UstawieniaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustawienia/dzien': {
      id: '/ustawienia/dzien'
      path: '/ustawienia/dzien'
      fullPath: '/ustawienia/dzien'
      preLoaderRoute: typeof UstawieniaDzienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustawienia/konto': {
      id: '/ustawienia/konto'
      path: '/ustawienia/konto'
      fullPath: '/ustawienia/konto'
      preLoaderRoute: typeof UstawieniaKontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustawienia/nakladka': {
      id: '/ustawienia/nakladka'
      path: '/ustawienia/nakladka'
      fullPath: '/ustawienia/nakladka'
      preLoaderRoute: typeof UstawieniaNakladkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustawienia/powiadomienia': {
      id: '/ustawienia/powiadomienia'
      path: '/ustawienia/powiadomienia'
      fullPath: '/ustawienia/powiadomienia'
      preLoaderRoute: typeof UstawieniaPowiadomieniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustawienia/profil': {
      id: '/ustawienia/profil'
      path: '/ustawienia/profil'
      fullPath: '/ustawienia/profil'
      preLoaderRoute: typeof UstawieniaProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustawienia/uprawnienia': {
      id: '/ustawienia/uprawnienia'
      path: '/ustawienia/uprawnienia'
      fullPath: '/ustawienia/uprawnienia'
      preLoaderRoute: typeof UstawieniaUprawnieniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustawienia/wyglad': {
      id: '/ustawienia/wyglad'
      path: '/ustawienia/wyglad'
      fullPath: '/ustawienia/wyglad'
      preLoaderRoute: typeof UstawieniaWygladRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DzienRoute: DzienRoute,
  StatystykiRoute: StatystykiRoute,
  WioskaRoute: WioskaRoute,
  ZadaniaRoute: ZadaniaRoute,
  SkupienieAplikacjeRoute: SkupienieAplikacjeRoute,
  UstawieniaDzienRoute: UstawieniaDzienRoute,
  UstawieniaKontoRoute: UstawieniaKontoRoute,
  UstawieniaNakladkaRoute: UstawieniaNakladkaRoute,
  UstawieniaPowiadomieniaRoute: UstawieniaPowiadomieniaRoute,
  UstawieniaProfilRoute: UstawieniaProfilRoute,
  UstawieniaUprawnieniaRoute: UstawieniaUprawnieniaRoute,
  UstawieniaWygladRoute: UstawieniaWygladRoute,
  SkupienieIndexRoute: SkupienieIndexRoute,
  UstawieniaIndexRoute: UstawieniaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
